name: academia_do_flutter
description: A sample command-line application.
version: 3.3.8
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
